# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BlogBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        main:
            entity:
                class: BlogBundle\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: blog_login
                check_path: blog_login_check
                default_target_path: blog_homepage
            logout:
                path: blog_logout
                target: blog_login

    access_control:
      # require ROLE_ADMIN for /admin*
      - { path: /admin, roles: ROLE_ADMIN }
