<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getById($id)
  {
    try{
      $article = $this
        ->createQueryBuilder('p')
        ->where('p.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getSingleResult();

        return $article;
    } catch (\Exception $ex){
         return null;
    }
  }

  public function getLastFive()
  {
    try{
      $articles = $this
        ->createQueryBuilder('p')
        ->orderby('p.postDate', 'DESC')
        ->getQuery()
        ->getResult();

        return $articles;
    } catch (\Exception $ex){
         return null;
    }
  }

  public function getList($page=1, $maxperpage=2)
  {
    $q = $this->_em->createQueryBuilder()
        ->select('article')
        ->from('BlogBundle:Article','article');

    $q->setFirstResult(($page-1) * $maxperpage)
      ->setMaxResults($maxperpage);
    return new Paginator($q);
  }

  public function getTotal()
  {
    try{
      $total = $this
        ->createQueryBuilder('q')
        ->select('count(q)')
        ->getQuery()
        ->getSingleScalarResult();

        return $total;
    } catch (\Exception $ex){
         return null;
    }
  }

  public function getListByCategory($page=1, $maxperpage=2, $category)
  {
    $q = $this->_em->createQueryBuilder()
        ->select('article')
        ->from('BlogBundle:Article','article')
        ->where('article.category = :category');

    $q->setParameter('category', $category);

    $q->setFirstResult(($page-1) * $maxperpage)
        ->setMaxResults($maxperpage);
    return new Paginator($q);
  }

  public function getTotalByCategory($category)
  {
    try{
      $total = $this
        ->createQueryBuilder('q')
        ->select('count(q)')
        ->where('q.category = :category')
        ->setParameter('category', $category)
        ->getQuery()
        ->getSingleScalarResult();

        return $total;
    } catch (\Exception $ex){
         return null;
    }
  }

  public function getListBySearch($page=1, $maxperpage=2, $title, $tag)
  {
    $q = $this->_em->createQueryBuilder()
        ->select('article')
        ->from('BlogBundle:Article','article')
        ->innerJoin('article.tags', 'a');

    if(isset($name)){
        $q->andWhere('article.title = :title')
            ->setParameter('title', $title);
    }
    if(isset($tag)) {
        $q->andWhere('article.tag = :tag')
            ->setParameter('tag', $tag);
    }

    $q->orderBy('article.postDate', 'DESC');

    $q->setFirstResult(($page-1) * $maxperpage)
        ->setMaxResults($maxperpage);

    return new Paginator($q);
  }

  public function getTotalBySearch($title, $tag)
  {
    $tags = new \Doctrine\Common\Collections\ArrayCollection();
    try{
      $total = $this
        ->createQueryBuilder('q')
        ->select('count(q)')
        ->innerJoin('q.tags', 'a');

      if(isset($title)){
          $total->andWhere('q.title = :title')
              ->setParameter('title', $title);
      }
      if(isset($tag)) {
        $tags[] = $tag;
          $total->andWhere('q.tags = :tag')
              ->setParameter('tag', $tags);
      }

      $total->getQuery()
        ->getSingleScalarResult();

      echo($total);
      die;

        return $total->getFirstResult();
    } catch (\Exception $ex){
        echo($ex);
        die;
         return null;
    }
  }
}
