blog_homepage:
    path:     /
    defaults:
        _controller:  BlogBundle:Article:index
        page:         null
        category_name:     null
    requirements:
        page:     \d*
        # category: \D

blog_list:
    path:     /article/list/{page}
    defaults:
        _controller:  BlogBundle:Article:index
        page:         1
        category_name:     null
    requirements:
        page:     \d*
        # category: \D

blog_list_by_category:
    path:     /article/listbycategory/{category_name}/{page}
    defaults:
        _controller:  BlogBundle:Article:index
        page:         1
    requirements:
        page:     \d*
        # category: \D

blog_categories:
    path:     /categories
    defaults:
        _controller:  BlogBundle:Category:index

blog_view:
    path:     /article/{id}
    defaults: { _controller: BlogBundle:Article:view }
    requirements:
        id:    \d+

blog_add_article:
    path:     admin/article/add
    defaults: { _controller: BlogBundle:Article:add }

blog_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: BlogBundle:Article:edit }
    requirements:
        id:    \d+

blog_add_tag:
    path:     admin/tag/add
    defaults: { _controller: BlogBundle:Tag:add }

blog_add_category:
    path:     admin/category/add
    defaults: { _controller: BlogBundle:Category:add }

blog_delete:
    path:     /admin/delete/{id}
    defaults: { _controller: BlogBundle:Article:delete }
    requirements:
        id:    \d+

blog_login:
    path: /login
    defaults: { _controller: BlogBundle:Security:login }

blog_login_check:
    path: /login_check

blog_logout:
    path:     /logout

blog_test:
    path:     /test
    defaults: { _controller: BlogBundle:Security:test }
