services:
    blog.comment_manager:
        class: BlogBundle\CommentManager\CommentManager
        arguments: ["@doctrine"]
    blog.comment_extension:
        class: BlogBundle\Twig\CommentExtension
        arguments: ["@blog.comment_manager"]
        public: false
        tags:
            - {name: twig.extension}
    blog.cookieMessage:
        class: BlogBundle\CookieMessage\CookieMessage

    blog.cookieListener:
        class: BlogBundle\CookieMessage\CookieListener
        arguments: ["@blog.cookieMessage"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processCookie }
